[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg_prime"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib_metadata; python_version>"3.10"'
]